### ISSUE TITLE
network seed explaniation

### ISSUE THREAD

**Issue by CoinDev** [sarchar/pyspv#1]
My high level understanding is that the spv wallet needs a trusted source to bootstrap itself onto the network.  I assume this is what the seeds are listed in the bitcoin.py.

What is going on here at the lower levels?  I am assuming they are full nodes with known tcp ports transmitting the bitcoin network protocol.  Is this correct?

Great project your developing here.

**Comment by sarchar** [comment]
Thanks.

The DNS seeds listed in Bitcoin.py are the same seeds provided in the Bitcoin Core reference client.  

These are only semi-trusted sources, and the issue of bootstrapping connectivity into the Bitcoin network is a big one.  These seeds are run by known members in the community (@sipa, bluematt, etc.).

At a lower level when connecting to the DNS, a lookup is performed for each of the seeds and they return several records of (IP,PORT) that are then added to the database of possible peers.
